// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserMgmtApi.Data;

namespace UserMgmtApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230816074357_initmigration")]
    partial class initmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("UserMgmtApi.Models.UserDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeType")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeType");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("PassportExpirtDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PassportFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PersonPhoto")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("UserMgmtApi.Models.UserDetail", b =>
                {
                    b.OwnsOne("UserMgmtApi.Models.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UserDetailId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .UseIdentityColumn();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Email");

                            b1.HasKey("UserDetailId");

                            b1.ToTable("UserDetails");

                            b1.WithOwner()
                                .HasForeignKey("UserDetailId");
                        });

                    b.OwnsOne("UserMgmtApi.Models.MobileNumber", "MobileNo", b1 =>
                        {
                            b1.Property<int>("UserDetailId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .UseIdentityColumn();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("MobileNo");

                            b1.HasKey("UserDetailId");

                            b1.ToTable("UserDetails");

                            b1.WithOwner()
                                .HasForeignKey("UserDetailId");
                        });

                    b.OwnsOne("UserMgmtApi.Models.Name", "Name", b1 =>
                        {
                            b1.Property<int>("UserDetailId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .UseIdentityColumn();

                            b1.Property<string>("Firstname")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Firstname");

                            b1.Property<string>("Lastname")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Lastname");

                            b1.HasKey("UserDetailId");

                            b1.ToTable("UserDetails");

                            b1.WithOwner()
                                .HasForeignKey("UserDetailId");
                        });

                    b.OwnsOne("UserMgmtApi.Models.PassportNumber", "PassportNo", b1 =>
                        {
                            b1.Property<int>("UserDetailId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .UseIdentityColumn();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PassportNo");

                            b1.HasKey("UserDetailId");

                            b1.ToTable("UserDetails");

                            b1.WithOwner()
                                .HasForeignKey("UserDetailId");
                        });

                    b.Navigation("Email");

                    b.Navigation("MobileNo");

                    b.Navigation("Name");

                    b.Navigation("PassportNo");
                });
#pragma warning restore 612, 618
        }
    }
}
